# config.yaml

# 应用基础配置
app:
  name: NutriScan
  version: "1.0.0"
  debug: false

# 数据库配置
database:
  type: sqlite
  path: sqlite:///nutriscan.db
  backup_dir: ./backup/database

# 存储配置
storage:
  # 图片存储相关配置
  images:
    path: ./resources/images
    allowed_types: [".jpg", ".jpeg", ".png"]
    max_size: 5242880  # 5MB in bytes
    thumbnail_size: [200, 200]
  
  # 日志配置
  logs:
    path: ./logs
    level: INFO
    max_size: 10485760  # 10MB
    backup_count: 5

# 界面配置
ui:
  # 窗口配置
  window:
    title: NutriScan
    width: 800
    height: 600
    min_width: 600
    min_height: 400
    icon: ./resources/icons/app.ico
  
  # 主题配置
  theme:
    name: default
    style_sheet: ./resources/styles/default.qss
    primary_color: "#2196F3"
    secondary_color: "#FFC107"

# 临时文件配置
temp:
  path: ./temp
  cleanup_on_exit: true